# The URL the site will be built for
base_url = "https://jingwiw.github.io/blog/"

title = "Jnwiki"
theme = "no-style-please"
license = "MIT"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Jingwiw"
# logo = "images/logo.png"
header_nav = [
    { name = "~home", url = "/" },
    { name = "~about", url = "/about" },
    { name = "#tags", url = "/tags" },
    { name = "+categories", url = "/categories" },
    { name = "@contexts", url = "/contexts" },
]
footer_nav = [
    { name = "< previous", url = "#" },
    { name = "webring", url = "#" },
    { name = "next >", url = "#" },
]
